### ISSUE TITLE
cosmiconfig throws error when searching for config

### ISSUE THREAD

**Issue by rossknudsen** [davidtheclark/cosmiconfig#235]
Hi, I've just started using this library in a vscode extension that I've been working on.  I need to find the Jest configuration in a particular directory and `cosmiconfig` seemed like the ideal solution.  This is the utility function that I've written - let me know if I've got something wrong:

```ts
const getJestConfigInDirectory = async (directory: string): Promise<string | null> => {
  const result = await cosmiconfig("jest").search(directory);
  if (result === null) {
    return null;
  }
  // TODO in future we may be able to make use of the config object that is returned.
  return result.filepath;
};
```
But basically I'm finding that the `search` call is throwing an error.  The error seems to be happening in the `loadJs` loader in the statement:
```ts
const result = importFresh(filepath);
```
So the issue _may_ be in a `import-fresh`.  The actual error is:

> [TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.dirname (path.js:583:5)
	at c:\Users\rossk\Documents\source\vscode-jest-test-adapter\dist\extension.js:63551:36
	at loadJs (c:\Users\rossk\Documents\source\vscode-jest-test-adapter\dist\extension.js:57684:18)
	at Explorer.loadFileContent (c:\Users\rossk\Documents\source\vscode-jest-test-adapter\dist\extension.js:57119:32)
	at Explorer.createCosmiconfigResult (c:\Users\rossk\Documents\source\vscode-jest-test-adapter\dist\extension.js:57124:36)
	at Explorer.loadSearchPlace (c:\Users\rossk\Documents\source\vscode-jest-test-adapter\dist\extension.js:57105:31)
	at async Explorer.searchDirectory (c:\Users\rossk\Documents\source\vscode-jest-test-adapter\dist\extension.js:57076:29)
	at async run (c:\Users\rossk\Documents\source\vscode-jest-test-adapter\dist\extension.js:57049:22)
	at async cacheWrapper (c:\Users\rossk\Documents\source\vscode-jest-test-adapter\dist\extension.js:57462:18)
	at async Explorer.search (c:\Users\rossk\Documents\source\vscode-jest-test-adapter\dist\extension.js:57041:20)]

Debugging further indicates that `import-fresh` tries to find the parent path of itself which happens to return `undefined` - which causes the later error.  Please let me know if this is something you are aware of, or if you think I need to raise this issue against `import-fresh` instead.

**Comment by rossknudsen** [comment]
Ah, it may have been a transient error.  Can't repro now...

**Comment by JulienKode** [comment]
I currently have the same issue when I use babel it's ok but when I use `ncc` to pack I have this error
